### ISSUE TITLE
Added KubeJS Wood Recipes consume Saws

### ISSUE THREAD

**Issue by Dinerell** [sharkweekthings/plastek#2]
I don't know if this is known but if you want to adress this you can add `.damageIngredient('#natprog:saw')` at the end of the recipes this works at least for the Shapeless Recipes. You can as well see it on the legacy site of the KubeJS wiki [here](https://wiki.latvian.dev/books/kubejs-legacy/page/recipeeventjs) . I already tested this as it could have been changed or removed!

**Comment by sharkweekthings** [comment]
Thanks! I actually asked on the KubeJS Discord and got the same answer just the other day, and actually have this fixed in v1.14.  

Thank you for letting me know!
