### ISSUE TITLE
Overencumbered 2 breaks movement until reload

### ISSUE THREAD

**Issue by CSHasty** [sharkweekthings/plastek#3]
Not sure if mod or modpack issue, but jumping or possibly waiting long enough while having Overencumbered 2 leads to movement becoming impossible until I reload my world.

**Comment by sharkweekthings** [comment]
Following up from your message in the Discord - we determined that this is just normal behavior of Supplementaries mod.

If you have 2 or more sacks in your inventory -- the Overencumbered buff will occur. You need to get rid of sacks in your inventory.
