### ISSUE TITLE
Ancient Debris Fortune Bug

### ISSUE THREAD

**Issue by Quarris** [sharkweekthings/plastek#5]
Ancient Debris works with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine with fortune to give you more ancient debris which you can place down and then mine to have pretty much infinite ancient debris. I think you get it

**Comment by sharkweekthings** [comment]
Lol!

this should now be resolved as I've removed ancient debris from block_drop.js, so the loot from the block will now be handled through Vanilla means.
